environment_config: {
  execution_config: {
    subnetwork_uri: "subnet-placeholder"
    authentication_config: {
        user_workload_authentication_type: SYSTEM_SERVICE_ACCOUNT
    }
  }
}
runtime_config: {
  version: "2.2"
}
